### ISSUE TITLE
cern: 'Groups' not available

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inveniosoftware/invenio-oauthclient#128]
```
Traceback (most recent call last):
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/views/client.py", line 128, in authorized
    return current_oauthclient.handlers[remote_app]()
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/flask_oauthlib/client.py", line 703, in decorated
    return f(*((data,) + args), **kwargs)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/handlers.py", line 503, in inner
    return f(args[0], remote, *args[1:], **kwargs)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/handlers.py", line 235, in inner
    return f(*args, **kwargs)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/handlers.py", line 343, in authorized_signup_handler
    account_setup = handlers['setup'](token, resp)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/handlers.py", line 505, in inner
    return f(remote, *args, **kwargs)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/contrib/cern.py", line 317, in account_setup
    groups = account_groups(token.remote_account, resource)
  File "/Users/ioannistsanaktsidis/Envs/cap-new/lib/python2.7/site-packages/invenio_oauthclient/contrib/cern.py", line 218, in account_groups
    groups = fetch_groups(resource['Group'])
KeyError: 'Group'
```
There is a problem with CERN Oauth as the Groups are not returned in resource. The problem comes from CERN Oauth service. Anyone experiencing the same issue ? Any workaround on this?

**Comment by hachreak** [comment]
In CDSlabs we had this issue at some point.
I thought they fixed. Maybe we should ask again if there are any new changes. :smile:

**Comment by ioannistsanaktsidis** [comment]
@hachreak  for us also sometimes it works, sometimes it breaks for 2 days and works again... I guess we can ask them :)

**Comment by egabancho** [comment]
@ioannistsanaktsidis are you still having this issue?
Two weeks ago they made a change in the service which introduced this bug but I've been told that is it fixed, at least for us it seems to work.

**Comment by ioannistsanaktsidis** [comment]
I don't see it anymore, so I guess we can close this and reopen it if it occurs again for someone.
