### ISSUE TITLE
docs: readthedocs does not render conf/APIs sections

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauthclient#146]
http://invenio-oauthclient.readthedocs.io/en/latest/configuration.html

and

http://invenio-oauthclient.readthedocs.io/en/latest/api.html#handlers

are both empty

**Comment by hachreak** [comment]
I found these warnings on readthedocs:

```
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:31: WARNING: autodoc: failed to import module u'invenio_oauthclient.handlers'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 34, in <module>
    from .handlers import authorized_default_handler, disconnect_handler, \
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/handlers.py", line 36, in <module>
    from invenio_db import db
ImportError: No module named invenio_db
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:37: WARNING: autodoc: failed to import module u'invenio_oauthclient.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:43: WARNING: autodoc: failed to import module u'invenio_oauthclient.views'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:49: WARNING: autodoc: failed to import module u'invenio_oauthclient.views.client'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:55: WARNING: autodoc: failed to import module u'invenio_oauthclient.views.settings'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:62: WARNING: autodoc: failed to import module u'invenio_oauthclient.signals'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:68: WARNING: autodoc: failed to import module u'invenio_oauthclient.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/api.rst:74: WARNING: autodoc: failed to import module u'invenio_oauthclient.errors'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/configuration.rst:28: WARNING: autodoc: failed to import module u'invenio_oauthclient.config'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/usage.rst:31: WARNING: autodoc: failed to import module u'invenio_oauthclient.contrib.github'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/usage.rst:36: WARNING: autodoc: failed to import module u'invenio_oauthclient.contrib.orcid'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/usage.rst:41: WARNING: autodoc: failed to import module u'invenio_oauthclient.contrib.cern'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/checkouts/latest/docs/usage.rst:46: WARNING: autodoc: failed to import module u'invenio_oauthclient'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/__init__.py", line 29, in <module>
    from .ext import InvenioOAuthClient
  File "/home/docs/checkouts/readthedocs.org/user_builds/invenio-oauthclient/envs/latest/lib/python2.7/site-packages/invenio_oauthclient-1.0.0a14.dev20170511-py2.7.egg/invenio_oauthclient/ext.py", line 33, in <module>
    from . import config
ImportError: cannot import name config
```

**Comment by lnielsen** [comment]
@hachreak Do you have a PR?

**Comment by hachreak** [comment]
closed by https://github.com/inveniosoftware/invenio-oauthclient/pull/147 :+1:
